=== tomptaylor/protobuf/track-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/object_02",
  "definitions": {
    "object_01": {
      "title": "attribObj",
      "type": "object",
      "required": [
        "idx",
        "flags"
      ],
      "additionalProperties": false,
      "properties": {
        "idx": {
          "type": "number"
        },
        "flags": {
          "$ref": "#/definitions/array_01"
        }
      }
    },
    "object_02": {
      "type": "object",
      "required": [
        "dept",
        "dest",
        "tid",
        "sid",
        "filters",
        "hash",
        "attribs",
        "diverted",
        "origDest",
        "origDept",
        "counter",
        "ts",
        "radar",
        "prevCallsign",
        "divertCheck",
        "delta",
        "route",
        "path",
        "eta",
        "callsign",
        "vip",
        "gov",
        "ga",
        "commercial",
        "acftISO",
        "iasa",
        "carrier",
        "tfmdgOnly",
        "sensors",
        "sensorList",
        "prevPos",
        "lon",
        "lat",
        "speed",
        "heading",
        "alt",
        "altType",
        "acftType",
        "mode3",
        "emergency",
        "gv",
        "domestic",
        "outbound",
        "inbound",
        "overflight",
        "foreign",
        "filter",
        "tsaIntl",
        "flags",
        "attribObj",
        "type"
      ],
      "additionalProperties": false,
      "properties": {
        "dept": {
          "type": "object",
          "required": [
            "type",
            "dom",
            "arpt",
            "iso",
            "src"
          ],
          "additionalProperties": false,
          "properties": {
            "type": {
              "type": "number"
            },
            "dom": {
              "type": "boolean"
            },
            "arpt": {
              "type": "string"
            },
            "iso": {
              "type": "string"
            },
            "src": {
              "type": "string"
            }
          }
        },
        "dest": {
          "type": "object",
          "required": [
            "type",
            "dom",
            "arpt",
            "iso",
            "src"
          ],
          "additionalProperties": false,
          "properties": {
            "type": {
              "type": "number"
            },
            "dom": {
              "type": "boolean"
            },
            "arpt": {
              "type": "string"
            },
            "iso": {
              "type": "string"
            },
            "src": {
              "type": "string"
            }
          }
        },
        "tid": {
          "type": "number"
        },
        "sid": {
          "type": "string"
        },
        "filters": {
          "title": "filters",
          "type": "object",
          "required": [
            "vip",
            "gov",
            "tfmdg",
            "callsign",
            "beacon"
          ],
          "additionalProperties": false,
          "properties": {
            "vip": {
              "type": "boolean"
            },
            "gov": {
              "type": "boolean"
            },
            "tfmdg": {
              "type": "boolean"
            },
            "callsign": {
              "type": "boolean"
            },
            "beacon": {
              "type": "boolean"
            }
          }
        },
        "hash": {
          "title": "hash",
          "type": "object",
          "required": [
            "path",
            "arpt",
            "pos"
          ],
          "additionalProperties": false,
          "properties": {
            "path": {
              "type": "string"
            },
            "arpt": {
              "type": "string",
              "format": "uri"
            },
            "pos": {
              "type": "string"
            }
          }
        },
        "attribs": {
          "type": "number"
        },
        "diverted": {
          "type": "boolean"
        },
        "origDest": {
          "type": "null"
        },
        "origDept": {
          "type": "null"
        },
        "counter": {
          "type": "number"
        },
        "ts": {
          "type": "string"
        },
        "radar": {
          "title": "radar",
          "type": "object",
          "required": [
            "primary",
            "beacon",
            "reinforced",
            "coasting",
            "tfmdg",
            "adsb",
            "link16",
            "etd",
            "ais",
            "manual",
            "correlated",
            "sorted"
          ],
          "additionalProperties": false,
          "properties": {
            "primary": {
              "type": "boolean"
            },
            "beacon": {
              "type": "boolean"
            },
            "reinforced": {
              "type": "boolean"
            },
            "coasting": {
              "type": "boolean"
            },
            "tfmdg": {
              "type": "boolean"
            },
            "adsb": {
              "type": "boolean"
            },
            "link16": {
              "type": "boolean"
            },
            "etd": {
              "type": "boolean"
            },
            "ais": {
              "type": "boolean"
            },
            "manual": {
              "type": "boolean"
            },
            "correlated": {
              "type": "boolean"
            },
            "sorted": {
              "type": "boolean"
            }
          }
        },
        "prevCallsign": {
          "type": "boolean"
        },
        "divertCheck": {
          "type": "boolean"
        },
        "delta": {
          "type": "number"
        },
        "route": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "eta": {
          "type": "number"
        },
        "callsign": {
          "type": "string"
        },
        "vip": {
          "type": "boolean"
        },
        "gov": {
          "type": "boolean"
        },
        "ga": {
          "type": "boolean"
        },
        "commercial": {
          "type": "boolean"
        },
        "acftISO": {
          "type": "boolean"
        },
        "iasa": {
          "type": "boolean"
        },
        "carrier": {
          "title": "carrier",
          "type": "object",
          "required": [
            "icao",
            "attribs"
          ],
          "additionalProperties": false,
          "properties": {
            "icao": {
              "type": "string"
            },
            "attribs": {
              "type": "number"
            }
          }
        },
        "tfmdgOnly": {
          "type": "boolean"
        },
        "sensors": {
          "type": "string"
        },
        "sensorList": {
          "type": "array",
          "title": "sensorList",
          "items": {
            "type": "string"
          }
        },
        "prevPos": {
          "$ref": "#/definitions/array_01"
        },
        "lon": {
          "type": "number"
        },
        "lat": {
          "type": "number"
        },
        "speed": {
          "type": "number"
        },
        "heading": {
          "type": "number"
        },
        "alt": {
          "type": "number"
        },
        "altType": {
          "type": "number"
        },
        "acftType": {
          "type": "string"
        },
        "mode3": {
          "type": "number"
        },
        "emergency": {
          "type": "boolean"
        },
        "gv": {
          "type": "boolean"
        },
        "domestic": {
          "type": "boolean"
        },
        "outbound": {
          "type": "boolean"
        },
        "inbound": {
          "type": "boolean"
        },
        "overflight": {
          "type": "boolean"
        },
        "foreign": {
          "type": "boolean"
        },
        "filter": {
          "type": "number"
        },
        "tsaIntl": {
          "type": "boolean"
        },
        "flags": {
          "type": "number"
        },
        "attribObj": {
          "$ref": "#/definitions/object_01"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "array_01": {
      "type": "array",
      "items": {
        "type": "number"
      }
    }
  }
}

=== tomptaylor/protobuf/track..json
{"dept":{"type":1,"dom":true,"arpt":"PHX","iso":"US","src":"KPHX"},"dest":{"type":1,"dom":true,"arpt":"MDW","iso":"US","src":"KMDW"},"tid":1,"sid":"3A3A0A58","filters":{"vip":false,"gov":false,"tfmdg":false,"callsign":false,"beacon":false},"hash":{"path":" 33.4342 -112.012 35.1013 -106.692 40.135 -92.5917 41.7861 -87.7525","arpt":"KPHX:KMDW:","pos":"-101.337:37.2868"},"attribs":80,"diverted":false,"origDest":null,"origDept":null,"counter":42,"ts":"1585253389254","radar":{"primary":false,"beacon":false,"reinforced":true,"coasting":false,"tfmdg":true,"adsb":true,"link16":false,"etd":false,"ais":false,"manual":false,"correlated":true,"sorted":false},"prevCallsign":false,"divertCheck":false,"delta":16385,"route":"KPHX./.ABQ052007..IRK.ENDEE4.KMDW/2132","path":"-106.692|35.1013*-92.5917|40.135*-87.7525|41.7861","eta":0,"callsign":"SWA2333","vip":false,"gov":false,"ga":false,"commercial":true,"acftISO":false,"iasa":false,"carrier":{"icao":"SWA","attribs":80},"tfmdgOnly":false,"sensors":"ADSB AMA-ZAB GCK-ZKC HTI-ZKC QOT-ZKC QWC-ZAB TAD-ZDV TFMDGV2","sensorList":["ADSB","AMA-ZAB","GCK-ZKC","HTI-ZKC","QOT-ZKC","QWC-ZAB","TAD-ZDV","TFMDGV2"],"prevPos":[-101.337,37.2868],"lon":-101.337,"lat":37.2868,"speed":561,"heading":59,"alt":410,"altType":1,"acftType":"B737","mode3":2665,"emergency":false,"gv":false,"domestic":true,"outbound":false,"inbound":false,"overflight":false,"foreign":false,"filter":1,"tsaIntl":false,"flags":7,"attribObj":{"idx":7,"flags":[28,32,5,0,16,1,0]},"type":"merge"}
